DM-17550: Considerations around alert schemata
lsst-dm/dmtn-093 pull request #4
Opened 2019-01-31 01:15 UTC by jdswinbank

2019-02-02 00:28 UTC, ebellm requested changes
a few points on sample data

2019-02-02 00:28 UTC, ebellm commented on index.rst
> +The Confluent Schema Registry makes it possible for schemas to involve within a given *subject name* while enforcing the specificed compatibility model.
Do you mean "topic" rather than "subject?"  Also I think you mean "evolve," not "involve".  And "specified" rather than "specificed."

2019-02-02 00:28 UTC, ebellm commented on index.rst
> +Avro files with realistic data generated by the Simulations team follow these schemas and are available in the :file:`data/` directory of `lsst-dm/alert_stream`_ repository.
Lots of issues here: I don't think I would advertise the simulated data as very realistic, the current avro files in that data directory have the schemas embedded in them (contra the above), and of course we don't have a schema registry available.

More generally I wonder if we should think about where/how best to store sample data: Conceptually I think it would make more sense to store with the schemas (in `sample-avro-alert`) or in indendent dataset repositories rather than hanging off of `alert_stream`.

2019-02-02 00:52 UTC, ebellm commented on index.rst
> +The Confluent Schema Registry makes it possible for schemas to involve within a given *subject name* while enforcing the specificed compatibility model.
I see where the Confluent Schema Registry describing "subjects" now--it's a use specific to CSR, though, and so is unclear here.  I'd suggest that this whole paragraph could be omitted while awaiting an actual implementation, however.

2019-02-02 02:25 UTC, jdswinbank commented on index.rst
> +The Confluent Schema Registry makes it possible for schemas to involve within a given *subject name* while enforcing the specificed compatibility model.
Right — as you identify, subjects are a concept specific to the schema registry, and are distinct from topics. I'm assuming we'll use the latter to e.g. identify particular nights of observing (per ZTF).

I'll have to give some thought re whether I agree with this being unnecessary implementation detail. I'd like to capture as much detail as we can reasonably be confident of in this document, and I'm not sure this is of a different level from e.g. specifying the wire protocol, but I'll certainly reconsider & discuss before publishing.

And thanks, re the typos.

2019-02-02 02:26 UTC, jdswinbank commented on index.rst
> +Avro files with realistic data generated by the Simulations team follow these schemas and are available in the :file:`data/` directory of `lsst-dm/alert_stream`_ repository.
I agree with these comments. This text is preserved (possibly not quite verbatim) from the previous version of this document; I'm happy to rewrite it. Watch this space.

2019-02-02 04:27 UTC, ebellm commented on index.rst
> +The Confluent Schema Registry makes it possible for schemas to involve within a given *subject name* while enforcing the specificed compatibility model.
I was not suggesting that it's an implementation detail, I was saying that I think it's premature to be specific.  In other words I am not as confident that this is how we should do it and am hesitant to advertise public interfaces with undue certainty.

2019-02-06 05:23 UTC, jdswinbank commented on index.rst
> +The Confluent Schema Registry makes it possible for schemas to involve within a given *subject name* while enforcing the specificed compatibility model.
It's necessary that we have a space in which we can sketch out design concepts, without them becoming part of the baseline, and without them being regarded as a commitment to a specific interface. That's the role I see this document filling. However, if you're worried that external observers might see it as something more than that, we should discuss how to better manage external expectations and/or brainstorm about other, potentially more appropriate, places in which we can record design sketches.

2019-02-06 06:19 UTC, ebellm commented on index.rst
> +The Confluent Schema Registry makes it possible for schemas to involve within a given *subject name* while enforcing the specificed compatibility model.
I accept this clarification of document scope; we will need a more public-facing interface description for potential brokers in the relatively near future.  The DPDD seems somewhat natural, although the full stream is not a public product in the same way as the catalogs and alerts are.  Happy to brainstorm this.

2019-02-06 06:19 UTC, ebellm approved these changes

2019-02-07 00:04 UTC, merged